version: '3.3'
services:
    node:
        user: "1000"
        container_name: ts-chatgpt
        ports:
            - '18080:8080'
        build: ../
        tty: true
        volumes:
            - ../:/src/app
